In [35]:
#system
from tqdm import tqdm
from tqdm import tqdm_notebook

#base
import numpy as np
import pandas as pd

#model
import xgboost as xbg
import lightgbm as lgb
import catboost as cbt

#sklearn tools
from sklearn.metrics import f1_score, precision_score, recall_score, precision_recall_curve, roc_auc_score
from sklearn.model_selection import StratifiedKFold, KFold, RepeatedKFold
from sklearn.preprocessing import LabelEncoder

#others



import matplotlib.pyplot as plt
%matplotlib inline

In [36]:
train_set = pd.read_csv('input/train_set.csv')
test_set = pd.read_csv('input/test_set.csv')

In [37]:
train_set.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25317 entries, 0 to 25316
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         25317 non-null  int64 
 1   age        25317 non-null  int64 
 2   job        25317 non-null  object
 3   marital    25317 non-null  object
 4   education  25317 non-null  object
 5   default    25317 non-null  object
 6   balance    25317 non-null  int64 
 7   housing    25317 non-null  object
 8   loan       25317 non-null  object
 9   contact    25317 non-null  object
 10  day        25317 non-null  int64 
 11  month      25317 non-null  object
 12  duration   25317 non-null  int64 
 13  campaign   25317 non-null  int64 
 14  pdays      25317 non-null  int64 
 15  previous   25317 non-null  int64 
 16  poutcome   25317 non-null  object
 17  y          25317 non-null  int64 
dtypes: int64(9), object(9)
memory usage: 3.5+ MB


In [80]:
test_set.info()
test_set['y'] = -1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10852 entries, 0 to 10851
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   ID         10852 non-null  int64 
 1   age        10852 non-null  int64 
 2   job        10852 non-null  object
 3   marital    10852 non-null  object
 4   education  10852 non-null  object
 5   default    10852 non-null  object
 6   balance    10852 non-null  int64 
 7   housing    10852 non-null  object
 8   loan       10852 non-null  object
 9   contact    10852 non-null  object
 10  day        10852 non-null  int64 
 11  month      10852 non-null  object
 12  duration   10852 non-null  int64 
 13  campaign   10852 non-null  int64 
 14  pdays      10852 non-null  int64 
 15  previous   10852 non-null  int64 
 16  poutcome   10852 non-null  object
 17  y          10852 non-null  int64 
dtypes: int64(9), object(9)
memory usage: 1.5+ MB


In [73]:
train_set.corr()

ID       age   balance       day  duration  campaign  \
ID        1.000000  0.008465  0.032719 -0.020171  0.229149 -0.038265   
age       0.008465  1.000000  0.093740 -0.016070  0.000416  0.006171   
balance   0.032719  0.093740  1.000000  0.010245  0.026042 -0.010419   
day      -0.020171 -0.016070  0.010245  1.000000 -0.031946  0.168830   
duration  0.229149  0.000416  0.026042 -0.031946  1.000000 -0.087780   
campaign -0.038265  0.006171 -0.010419  0.168830 -0.087780  1.000000   
pdays     0.065807 -0.026431  0.001032 -0.092892  0.000040 -0.089224   
previous  0.047028  0.006575  0.015792 -0.050706  0.001315 -0.031667   
y         0.556627  0.029916  0.057564 -0.031886  0.394746 -0.075173   

             pdays  previous         y  
ID        0.065807  0.047028  0.556627  
age      -0.026431  0.006575  0.029916  
balance   0.001032  0.015792  0.057564  
day      -0.092892 -0.050706 -0.031886  
duration  0.000040  0.001315  0.394746  
campaign -0.089224 -0.031667 -0.075173  
pdays     1.000000  0.411688  0.107565  
previous  0.411688  1.000000  0.088337  
y         0.107565  0.088337  1.000000

In [74]:
train_set.job.value_counts()

blue-collar      5456
management       5296
technician       4241
admin.           2909
services         2342
retired          1273
self-employed     884
entrepreneur      856
unemployed        701
housemaid         663
student           533
unknown           163
Name: job, dtype: int64

In [81]:
data = train_set.append(test_set).reset_index(drop=True)
data.head()

ID  age         job   marital  education default  balance housing loan  \
0   1   43  management   married   tertiary      no      291     yes   no   
1   2   42  technician  divorced    primary      no     5076     yes   no   
2   3   47      admin.   married  secondary      no      104     yes  yes   
3   4   28  management    single  secondary      no     -994     yes  yes   
4   5   42  technician  divorced  secondary      no     2974     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome  y  
0   unknown    9   may       150         2     -1         0  unknown  0  
1  cellular    7   apr        99         1    251         2    other  0  
2  cellular   14   jul        77         2     -1         0  unknown  0  
3  cellular   18   jul       174         2     -1         0  unknown  0  
4   unknown   21   may       187         5     -1         0  unknown  0

In [82]:
cat_col = [i for i in data.select_dtypes(object).columns if i not in ['ID', 'y']]
for i in tqdm_notebook(cat_col):
    data['count_'+i] = data.groupby(i)[i].transform('count')
    lbl = LabelEncoder()
    data[i] = lbl.fit_transform(data[i].astype(str))

In [83]:
data.head()

ID  age  job  marital  education  default  balance  housing  loan  contact  \
0   1   43    4        1          2        0      291        1     0        2   
1   2   42    9        0          0        0     5076        1     0        0   
2   3   47    0        1          1        0      104        1     1        0   
3   4   28    4        2          1        0     -994        1     1        0   
4   5   42    9        0          1        0     2974        1     0        2   

   ...  y  count_job  count_marital  count_education  count_default  \
0  ...  0       7595          21857            10654          35524   
1  ...  0       6083           4140             5493          35524   
2  ...  0       4124          21857            18509          35524   
3  ...  0       7595          10172            18509          35524   
4  ...  0       6083           4140            18509          35524   

   count_housing  count_loan  count_contact  count_month  count_poutcome  
0          19959       30363          10393        10957           29554  
1          19959       30363          23437         2365            1475  
2          19959        5806          23437         5569           29554  
3          19959        5806          23437         5569           29554  
4          19959       30363          10393        10957           29554  

[5 rows x 27 columns]

In [84]:
feats = [i  for i in data.columns if i not in ['ID', 'y']]
feats

['age',
 'job',
 'marital',
 'education',
 'default',
 'balance',
 'housing',
 'loan',
 'contact',
 'day',
 'month',
 'duration',
 'campaign',
 'pdays',
 'previous',
 'poutcome',
 'count_job',
 'count_marital',
 'count_education',
 'count_default',
 'count_housing',
 'count_loan',
 'count_contact',
 'count_month',
 'count_poutcome']

In [85]:
model = lgb.LGBMClassifier(
    boosting_type='GBDT',
    num_leaves=30,
    n_estimators=1500,
    max_depth=-1,
    objective='binary',
    metric = 'auc',
    subsample= 0.95,
    subsample_freq=1,
    colsample_bytree=0.7,
    reg_alpha=0.,
    reg_lambda=0.,
    learning_rate=0.02,
    random_state=2017
)

In [89]:
train_x = data[data['y']!=-1][feats]
train_y = data[data['y']!=-1]['y']
test_x = data[data['y']==-1][feats]
train_x.shape, test_x.shape

((25317, 25), (10852, 25))

In [98]:
model.fit(train_x, train_y)
test_pre = model.predict_proba(test_x)

array([0.2742011, 0.7257989])

In [105]:
pre = data[data['y']==-1][['ID']]
pre['pred'] = test_pre[:, 1]
test_pre.shape, test_pre[0:5,:]

((10852, 2), array([[0.96517302, 0.03482698],
        [0.9944712 , 0.0055288 ],
        [0.99877612, 0.00122388],
        [0.25366374, 0.74633626],
        [0.9834217 , 0.0165783 ]]))

In [96]:
pre.head()

ID      pred
25317  25318  0.034827
25318  25319  0.005529
25319  25320  0.001224
25320  25321  0.746336
25321  25322  0.016578

In [114]:
n = 10
kfold = KFold(n_splits=n, shuffle=True, random_state=42)
list(kfold.split(train_x.iloc[1:20]))

[(array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
  array([0, 5])),
 (array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18]),
  array([ 1, 11])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 12, 13, 14, 15, 17, 18]),
  array([ 8, 16])),
 (array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18]),
  array([ 3, 13])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 16, 18]),
  array([15, 17])),
 (array([ 0,  1,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13, 14, 15, 16, 17, 18]),
  array([2, 9])),
 (array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17]),
  array([ 4, 18])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 13, 14, 15, 16, 17, 18]),
  array([ 7, 12])),
 (array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 15, 16, 17, 18]),
  array([10, 14])),
 (array([ 0,  1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
         18]), array([6]))]

In [116]:
res = data[data['y']==-1][['ID']]
res['pred'] = 0
for train_idx, val_idx in kfold.split(train_x):
    train_x1 = train_x.iloc[train_idx]
    train_y1 = train_y.iloc[train_idx]
    val_x1 = train_x.iloc[val_idx]
    val_y1 = train_y.iloc[val_idx]
    
    model.fit(train_x1,train_y1, eval_set=[(train_x1, train_y1), (val_x1, val_y1)], eval_metric='auc', early_stopping_rounds=100)
    res['pred'] += model.predict_proba(test_x)[:,1]
    
res['pred'] = res['pred']/kfold.n_splits

[1]	training's auc: 0.890209	valid_1's auc: 0.889424
Training until validation scores don't improve for 100 rounds
[2]	training's auc: 0.907021	valid_1's auc: 0.901357
[3]	training's auc: 0.912792	valid_1's auc: 0.903343
[4]	training's auc: 0.918829	valid_1's auc: 0.907438
[5]	training's auc: 0.927566	valid_1's auc: 0.916754
[6]	training's auc: 0.927007	valid_1's auc: 0.916028
[7]	training's auc: 0.929015	valid_1's auc: 0.916161
[8]	training's auc: 0.929083	valid_1's auc: 0.916183
[9]	training's auc: 0.928682	valid_1's auc: 0.914413
[10]	training's auc: 0.930162	valid_1's auc: 0.915446
[11]	training's auc: 0.930555	valid_1's auc: 0.916745
[12]	training's auc: 0.930514	valid_1's auc: 0.916715
[13]	training's auc: 0.930821	valid_1's auc: 0.917079
[14]	training's auc: 0.931772	valid_1's auc: 0.917735
[15]	training's auc: 0.931979	valid_1's auc: 0.91821
[16]	training's auc: 0.932164	valid_1's auc: 0.918187
[17]	training's auc: 0.932336	valid_1's auc: 0.919179
[18]	training's auc: 0.933709	

[151]	training's auc: 0.950798	valid_1's auc: 0.932299
[152]	training's auc: 0.950823	valid_1's auc: 0.932337
[153]	training's auc: 0.950898	valid_1's auc: 0.932397
[154]	training's auc: 0.951056	valid_1's auc: 0.93243
[155]	training's auc: 0.951147	valid_1's auc: 0.932417
[156]	training's auc: 0.951261	valid_1's auc: 0.93239
[157]	training's auc: 0.951309	valid_1's auc: 0.932352
[158]	training's auc: 0.951359	valid_1's auc: 0.932405
[159]	training's auc: 0.951442	valid_1's auc: 0.932462
[160]	training's auc: 0.951514	valid_1's auc: 0.932486
[161]	training's auc: 0.951616	valid_1's auc: 0.932462
[162]	training's auc: 0.951685	valid_1's auc: 0.932453
[163]	training's auc: 0.951762	valid_1's auc: 0.932393
[164]	training's auc: 0.951792	valid_1's auc: 0.932448
[165]	training's auc: 0.951888	valid_1's auc: 0.932493
[166]	training's auc: 0.951946	valid_1's auc: 0.93249
[167]	training's auc: 0.95198	valid_1's auc: 0.932495
[168]	training's auc: 0.952065	valid_1's auc: 0.932421
[169]	training

[300]	training's auc: 0.961274	valid_1's auc: 0.933303
[301]	training's auc: 0.961342	valid_1's auc: 0.933269
[302]	training's auc: 0.961411	valid_1's auc: 0.933215
[303]	training's auc: 0.961472	valid_1's auc: 0.933356
[304]	training's auc: 0.961546	valid_1's auc: 0.933325
[305]	training's auc: 0.96161	valid_1's auc: 0.933331
[306]	training's auc: 0.961679	valid_1's auc: 0.933347
[307]	training's auc: 0.961753	valid_1's auc: 0.933343
[308]	training's auc: 0.961799	valid_1's auc: 0.933368
[309]	training's auc: 0.961942	valid_1's auc: 0.933334
[310]	training's auc: 0.962005	valid_1's auc: 0.933306
[311]	training's auc: 0.962067	valid_1's auc: 0.933256
[312]	training's auc: 0.962126	valid_1's auc: 0.933269
[313]	training's auc: 0.962232	valid_1's auc: 0.933263
[314]	training's auc: 0.962308	valid_1's auc: 0.933271
[315]	training's auc: 0.9624	valid_1's auc: 0.933322
[316]	training's auc: 0.962481	valid_1's auc: 0.933318
[317]	training's auc: 0.962557	valid_1's auc: 0.933272
[318]	trainin

[449]	training's auc: 0.969716	valid_1's auc: 0.933443
[450]	training's auc: 0.969766	valid_1's auc: 0.933435
[451]	training's auc: 0.969824	valid_1's auc: 0.933434
[452]	training's auc: 0.969893	valid_1's auc: 0.93339
[453]	training's auc: 0.969929	valid_1's auc: 0.933407
[454]	training's auc: 0.969975	valid_1's auc: 0.933434
[455]	training's auc: 0.970035	valid_1's auc: 0.933435
[456]	training's auc: 0.970073	valid_1's auc: 0.933418
[457]	training's auc: 0.970123	valid_1's auc: 0.933421
[458]	training's auc: 0.970191	valid_1's auc: 0.933463
[459]	training's auc: 0.970236	valid_1's auc: 0.933478
[460]	training's auc: 0.970278	valid_1's auc: 0.933471
[461]	training's auc: 0.970339	valid_1's auc: 0.933531
[462]	training's auc: 0.970385	valid_1's auc: 0.933547
[463]	training's auc: 0.970428	valid_1's auc: 0.933565
[464]	training's auc: 0.970473	valid_1's auc: 0.93359
[465]	training's auc: 0.970524	valid_1's auc: 0.933558
[466]	training's auc: 0.970557	valid_1's auc: 0.933563
[467]	traini

[598]	training's auc: 0.976093	valid_1's auc: 0.933743
[599]	training's auc: 0.976128	valid_1's auc: 0.933739
[600]	training's auc: 0.976175	valid_1's auc: 0.933756
[601]	training's auc: 0.976221	valid_1's auc: 0.933786
[602]	training's auc: 0.976251	valid_1's auc: 0.933765
[603]	training's auc: 0.976298	valid_1's auc: 0.933762
[604]	training's auc: 0.976341	valid_1's auc: 0.933755
[605]	training's auc: 0.976382	valid_1's auc: 0.933808
[606]	training's auc: 0.97642	valid_1's auc: 0.93382
[607]	training's auc: 0.976452	valid_1's auc: 0.93382
[608]	training's auc: 0.976489	valid_1's auc: 0.933768
[609]	training's auc: 0.976506	valid_1's auc: 0.933793
[610]	training's auc: 0.976554	valid_1's auc: 0.933798
[611]	training's auc: 0.976573	valid_1's auc: 0.933826
[612]	training's auc: 0.976609	valid_1's auc: 0.933864
[613]	training's auc: 0.976659	valid_1's auc: 0.933859
[614]	training's auc: 0.976707	valid_1's auc: 0.933845
[615]	training's auc: 0.976743	valid_1's auc: 0.933834
[616]	trainin

[747]	training's auc: 0.981165	valid_1's auc: 0.933948
[748]	training's auc: 0.98119	valid_1's auc: 0.933926
[749]	training's auc: 0.981215	valid_1's auc: 0.933937
[750]	training's auc: 0.981251	valid_1's auc: 0.933917
[751]	training's auc: 0.981287	valid_1's auc: 0.933936
[752]	training's auc: 0.981319	valid_1's auc: 0.933961
[753]	training's auc: 0.981353	valid_1's auc: 0.933968
[754]	training's auc: 0.981387	valid_1's auc: 0.934005
[755]	training's auc: 0.981404	valid_1's auc: 0.933965
[756]	training's auc: 0.981425	valid_1's auc: 0.933926
[757]	training's auc: 0.98146	valid_1's auc: 0.933924
[758]	training's auc: 0.981488	valid_1's auc: 0.933965
[759]	training's auc: 0.981516	valid_1's auc: 0.93398
Early stopping, best iteration is:
[659]	training's auc: 0.978337	valid_1's auc: 0.934183
[1]	training's auc: 0.902706	valid_1's auc: 0.904911
Training until validation scores don't improve for 100 rounds
[2]	training's auc: 0.909508	valid_1's auc: 0.914731
[3]	training's auc: 0.917934	v

[136]	training's auc: 0.949097	valid_1's auc: 0.940293
[137]	training's auc: 0.94914	valid_1's auc: 0.940346
[138]	training's auc: 0.949209	valid_1's auc: 0.940371
[139]	training's auc: 0.949321	valid_1's auc: 0.9404
[140]	training's auc: 0.949434	valid_1's auc: 0.940434
[141]	training's auc: 0.949495	valid_1's auc: 0.940476
[142]	training's auc: 0.949544	valid_1's auc: 0.9405
[143]	training's auc: 0.949614	valid_1's auc: 0.940568
[144]	training's auc: 0.949684	valid_1's auc: 0.940546
[145]	training's auc: 0.949755	valid_1's auc: 0.940587
[146]	training's auc: 0.949822	valid_1's auc: 0.940642
[147]	training's auc: 0.949903	valid_1's auc: 0.940554
[148]	training's auc: 0.949952	valid_1's auc: 0.940597
[149]	training's auc: 0.950013	valid_1's auc: 0.940588
[150]	training's auc: 0.950134	valid_1's auc: 0.940555
[151]	training's auc: 0.950211	valid_1's auc: 0.940569
[152]	training's auc: 0.95026	valid_1's auc: 0.940548
[153]	training's auc: 0.95035	valid_1's auc: 0.940577
[154]	training's 

[285]	training's auc: 0.960037	valid_1's auc: 0.941484
[286]	training's auc: 0.960102	valid_1's auc: 0.941425
[287]	training's auc: 0.96014	valid_1's auc: 0.94144
[288]	training's auc: 0.960201	valid_1's auc: 0.941449
[289]	training's auc: 0.960265	valid_1's auc: 0.941426
[290]	training's auc: 0.96033	valid_1's auc: 0.941471
[291]	training's auc: 0.960386	valid_1's auc: 0.941471
[292]	training's auc: 0.960453	valid_1's auc: 0.941456
[293]	training's auc: 0.960508	valid_1's auc: 0.941429
[294]	training's auc: 0.960589	valid_1's auc: 0.941435
[295]	training's auc: 0.960639	valid_1's auc: 0.94144
[296]	training's auc: 0.96074	valid_1's auc: 0.941448
[297]	training's auc: 0.960818	valid_1's auc: 0.941422
[298]	training's auc: 0.960875	valid_1's auc: 0.941432
[299]	training's auc: 0.960952	valid_1's auc: 0.941465
[300]	training's auc: 0.961004	valid_1's auc: 0.941443
[301]	training's auc: 0.961078	valid_1's auc: 0.941404
[302]	training's auc: 0.961146	valid_1's auc: 0.941449
[303]	training'

Training until validation scores don't improve for 100 rounds
[2]	training's auc: 0.912751	valid_1's auc: 0.906447
[3]	training's auc: 0.916278	valid_1's auc: 0.907876
[4]	training's auc: 0.919673	valid_1's auc: 0.909121
[5]	training's auc: 0.925289	valid_1's auc: 0.91782
[6]	training's auc: 0.924903	valid_1's auc: 0.916036
[7]	training's auc: 0.928456	valid_1's auc: 0.918427
[8]	training's auc: 0.928426	valid_1's auc: 0.918676
[9]	training's auc: 0.927584	valid_1's auc: 0.91807
[10]	training's auc: 0.928527	valid_1's auc: 0.918239
[11]	training's auc: 0.928609	valid_1's auc: 0.91838
[12]	training's auc: 0.928477	valid_1's auc: 0.917918
[13]	training's auc: 0.928356	valid_1's auc: 0.917853
[14]	training's auc: 0.929983	valid_1's auc: 0.919186
[15]	training's auc: 0.930151	valid_1's auc: 0.91956
[16]	training's auc: 0.930503	valid_1's auc: 0.919105
[17]	training's auc: 0.930929	valid_1's auc: 0.919805
[18]	training's auc: 0.932318	valid_1's auc: 0.921189
[19]	training's auc: 0.932961	va

[152]	training's auc: 0.950447	valid_1's auc: 0.933401
[153]	training's auc: 0.950535	valid_1's auc: 0.93338
[154]	training's auc: 0.950613	valid_1's auc: 0.933354
[155]	training's auc: 0.950681	valid_1's auc: 0.933367
[156]	training's auc: 0.950819	valid_1's auc: 0.933403
[157]	training's auc: 0.950886	valid_1's auc: 0.933432
[158]	training's auc: 0.950934	valid_1's auc: 0.933504
[159]	training's auc: 0.950997	valid_1's auc: 0.933507
[160]	training's auc: 0.951038	valid_1's auc: 0.933557
[161]	training's auc: 0.951112	valid_1's auc: 0.93367
[162]	training's auc: 0.951178	valid_1's auc: 0.933663
[163]	training's auc: 0.951247	valid_1's auc: 0.933643
[164]	training's auc: 0.951297	valid_1's auc: 0.933721
[165]	training's auc: 0.951383	valid_1's auc: 0.933704
[166]	training's auc: 0.951431	valid_1's auc: 0.933698
[167]	training's auc: 0.95149	valid_1's auc: 0.933693
[168]	training's auc: 0.951585	valid_1's auc: 0.933679
[169]	training's auc: 0.951701	valid_1's auc: 0.933711
[170]	trainin

[301]	training's auc: 0.961159	valid_1's auc: 0.93661
[302]	training's auc: 0.96124	valid_1's auc: 0.936601
[303]	training's auc: 0.961327	valid_1's auc: 0.936665
[304]	training's auc: 0.961378	valid_1's auc: 0.936684
[305]	training's auc: 0.961435	valid_1's auc: 0.936684
[306]	training's auc: 0.961478	valid_1's auc: 0.93672
[307]	training's auc: 0.961515	valid_1's auc: 0.936751
[308]	training's auc: 0.961558	valid_1's auc: 0.936768
[309]	training's auc: 0.961614	valid_1's auc: 0.936691
[310]	training's auc: 0.96166	valid_1's auc: 0.936687
[311]	training's auc: 0.961723	valid_1's auc: 0.936729
[312]	training's auc: 0.961795	valid_1's auc: 0.936737
[313]	training's auc: 0.961849	valid_1's auc: 0.936769
[314]	training's auc: 0.961893	valid_1's auc: 0.936798
[315]	training's auc: 0.961951	valid_1's auc: 0.936838
[316]	training's auc: 0.962008	valid_1's auc: 0.936797
[317]	training's auc: 0.962077	valid_1's auc: 0.936826
[318]	training's auc: 0.962131	valid_1's auc: 0.936862
[319]	training

[450]	training's auc: 0.969209	valid_1's auc: 0.93732
[451]	training's auc: 0.969255	valid_1's auc: 0.937268
[452]	training's auc: 0.969298	valid_1's auc: 0.937274
[453]	training's auc: 0.969344	valid_1's auc: 0.937283
[454]	training's auc: 0.969394	valid_1's auc: 0.937246
[455]	training's auc: 0.969449	valid_1's auc: 0.937237
[456]	training's auc: 0.969505	valid_1's auc: 0.937187
[457]	training's auc: 0.969548	valid_1's auc: 0.937199
[458]	training's auc: 0.969597	valid_1's auc: 0.937168
[459]	training's auc: 0.969626	valid_1's auc: 0.937159
[460]	training's auc: 0.969684	valid_1's auc: 0.937154
[461]	training's auc: 0.969724	valid_1's auc: 0.937159
Early stopping, best iteration is:
[361]	training's auc: 0.964668	valid_1's auc: 0.937511
[1]	training's auc: 0.901286	valid_1's auc: 0.892843
Training until validation scores don't improve for 100 rounds
[2]	training's auc: 0.914278	valid_1's auc: 0.904858
[3]	training's auc: 0.917784	valid_1's auc: 0.910927
[4]	training's auc: 0.919611	v

[137]	training's auc: 0.949582	valid_1's auc: 0.930085
[138]	training's auc: 0.949658	valid_1's auc: 0.930088
[139]	training's auc: 0.949756	valid_1's auc: 0.930067
[140]	training's auc: 0.949859	valid_1's auc: 0.930102
[141]	training's auc: 0.949909	valid_1's auc: 0.930127
[142]	training's auc: 0.949963	valid_1's auc: 0.930039
[143]	training's auc: 0.950034	valid_1's auc: 0.930108
[144]	training's auc: 0.950134	valid_1's auc: 0.930029
[145]	training's auc: 0.950242	valid_1's auc: 0.930104
[146]	training's auc: 0.950343	valid_1's auc: 0.930126
[147]	training's auc: 0.950454	valid_1's auc: 0.930277
[148]	training's auc: 0.950496	valid_1's auc: 0.930232
[149]	training's auc: 0.950562	valid_1's auc: 0.930219
[150]	training's auc: 0.95066	valid_1's auc: 0.93027
[151]	training's auc: 0.950734	valid_1's auc: 0.930196
[152]	training's auc: 0.950786	valid_1's auc: 0.930251
[153]	training's auc: 0.950876	valid_1's auc: 0.930238
[154]	training's auc: 0.951017	valid_1's auc: 0.93027
[155]	trainin

[286]	training's auc: 0.960673	valid_1's auc: 0.932093
[287]	training's auc: 0.960723	valid_1's auc: 0.932085
[288]	training's auc: 0.960781	valid_1's auc: 0.932093
[289]	training's auc: 0.960852	valid_1's auc: 0.932127
[290]	training's auc: 0.9609	valid_1's auc: 0.93214
[291]	training's auc: 0.960967	valid_1's auc: 0.932131
[292]	training's auc: 0.961055	valid_1's auc: 0.932079
[293]	training's auc: 0.961115	valid_1's auc: 0.932057
[294]	training's auc: 0.961173	valid_1's auc: 0.93201
[295]	training's auc: 0.961247	valid_1's auc: 0.932
[296]	training's auc: 0.961306	valid_1's auc: 0.931985
[297]	training's auc: 0.961366	valid_1's auc: 0.931976
[298]	training's auc: 0.961416	valid_1's auc: 0.932003
[299]	training's auc: 0.961485	valid_1's auc: 0.93209
[300]	training's auc: 0.961561	valid_1's auc: 0.932103
[301]	training's auc: 0.961645	valid_1's auc: 0.932149
[302]	training's auc: 0.961703	valid_1's auc: 0.93214
[303]	training's auc: 0.96175	valid_1's auc: 0.932065
[304]	training's auc

[435]	training's auc: 0.969281	valid_1's auc: 0.932894
[436]	training's auc: 0.969335	valid_1's auc: 0.932854
[437]	training's auc: 0.969387	valid_1's auc: 0.932836
[438]	training's auc: 0.96943	valid_1's auc: 0.932811
[439]	training's auc: 0.969474	valid_1's auc: 0.932792
[440]	training's auc: 0.969513	valid_1's auc: 0.932786
[441]	training's auc: 0.969561	valid_1's auc: 0.932773
[442]	training's auc: 0.969606	valid_1's auc: 0.932767
[443]	training's auc: 0.969663	valid_1's auc: 0.932736
[444]	training's auc: 0.969727	valid_1's auc: 0.932723
[445]	training's auc: 0.969757	valid_1's auc: 0.932763
[446]	training's auc: 0.96979	valid_1's auc: 0.932726
[447]	training's auc: 0.969863	valid_1's auc: 0.932783
[448]	training's auc: 0.969907	valid_1's auc: 0.932788
[449]	training's auc: 0.969952	valid_1's auc: 0.932816
[450]	training's auc: 0.970023	valid_1's auc: 0.932782
[451]	training's auc: 0.970074	valid_1's auc: 0.932791
[452]	training's auc: 0.970112	valid_1's auc: 0.932792
[453]	traini

[50]	training's auc: 0.939559	valid_1's auc: 0.939149
[51]	training's auc: 0.939692	valid_1's auc: 0.939385
[52]	training's auc: 0.939803	valid_1's auc: 0.939406
[53]	training's auc: 0.939938	valid_1's auc: 0.93929
[54]	training's auc: 0.940095	valid_1's auc: 0.939216
[55]	training's auc: 0.940367	valid_1's auc: 0.939754
[56]	training's auc: 0.940545	valid_1's auc: 0.93963
[57]	training's auc: 0.940737	valid_1's auc: 0.939528
[58]	training's auc: 0.940863	valid_1's auc: 0.939418
[59]	training's auc: 0.940889	valid_1's auc: 0.939423
[60]	training's auc: 0.941009	valid_1's auc: 0.939464
[61]	training's auc: 0.941108	valid_1's auc: 0.93945
[62]	training's auc: 0.94125	valid_1's auc: 0.93945
[63]	training's auc: 0.941546	valid_1's auc: 0.939678
[64]	training's auc: 0.941687	valid_1's auc: 0.939761
[65]	training's auc: 0.941795	valid_1's auc: 0.939812
[66]	training's auc: 0.941828	valid_1's auc: 0.939762
[67]	training's auc: 0.941878	valid_1's auc: 0.939902
[68]	training's auc: 0.941971	val

[200]	training's auc: 0.95343	valid_1's auc: 0.943579
[201]	training's auc: 0.953502	valid_1's auc: 0.943678
[202]	training's auc: 0.95357	valid_1's auc: 0.943752
[203]	training's auc: 0.953625	valid_1's auc: 0.943861
[204]	training's auc: 0.953684	valid_1's auc: 0.943813
[205]	training's auc: 0.953743	valid_1's auc: 0.943842
[206]	training's auc: 0.953823	valid_1's auc: 0.943868
[207]	training's auc: 0.953918	valid_1's auc: 0.943828
[208]	training's auc: 0.953989	valid_1's auc: 0.943791
[209]	training's auc: 0.954057	valid_1's auc: 0.943746
[210]	training's auc: 0.954112	valid_1's auc: 0.943757
[211]	training's auc: 0.954201	valid_1's auc: 0.943772
[212]	training's auc: 0.954292	valid_1's auc: 0.94377
[213]	training's auc: 0.95435	valid_1's auc: 0.943775
[214]	training's auc: 0.954425	valid_1's auc: 0.943833
[215]	training's auc: 0.954497	valid_1's auc: 0.943837
[216]	training's auc: 0.954587	valid_1's auc: 0.943863
[217]	training's auc: 0.954659	valid_1's auc: 0.943876
[218]	training

[349]	training's auc: 0.963806	valid_1's auc: 0.944868
[350]	training's auc: 0.963876	valid_1's auc: 0.944875
[351]	training's auc: 0.963912	valid_1's auc: 0.944896
[352]	training's auc: 0.963983	valid_1's auc: 0.944873
[353]	training's auc: 0.964053	valid_1's auc: 0.94488
[354]	training's auc: 0.964104	valid_1's auc: 0.944925
[355]	training's auc: 0.964154	valid_1's auc: 0.944937
[356]	training's auc: 0.964209	valid_1's auc: 0.944923
[357]	training's auc: 0.964276	valid_1's auc: 0.944896
[358]	training's auc: 0.964342	valid_1's auc: 0.944852
[359]	training's auc: 0.964387	valid_1's auc: 0.944857
[360]	training's auc: 0.964453	valid_1's auc: 0.944859
[361]	training's auc: 0.9645	valid_1's auc: 0.944865
[362]	training's auc: 0.964566	valid_1's auc: 0.944814
[363]	training's auc: 0.964647	valid_1's auc: 0.944888
[364]	training's auc: 0.964718	valid_1's auc: 0.944848
[365]	training's auc: 0.964761	valid_1's auc: 0.944856
[366]	training's auc: 0.964812	valid_1's auc: 0.94483
[367]	training

[15]	training's auc: 0.930448	valid_1's auc: 0.928864
[16]	training's auc: 0.930545	valid_1's auc: 0.928684
[17]	training's auc: 0.930582	valid_1's auc: 0.929079
[18]	training's auc: 0.931538	valid_1's auc: 0.929877
[19]	training's auc: 0.931814	valid_1's auc: 0.929842
[20]	training's auc: 0.931896	valid_1's auc: 0.929629
[21]	training's auc: 0.932226	valid_1's auc: 0.930389
[22]	training's auc: 0.932394	valid_1's auc: 0.930716
[23]	training's auc: 0.932739	valid_1's auc: 0.930342
[24]	training's auc: 0.932842	valid_1's auc: 0.930231
[25]	training's auc: 0.933262	valid_1's auc: 0.930464
[26]	training's auc: 0.933446	valid_1's auc: 0.930909
[27]	training's auc: 0.933837	valid_1's auc: 0.931436
[28]	training's auc: 0.934053	valid_1's auc: 0.931651
[29]	training's auc: 0.934657	valid_1's auc: 0.931886
[30]	training's auc: 0.934795	valid_1's auc: 0.931772
[31]	training's auc: 0.934884	valid_1's auc: 0.932098
[32]	training's auc: 0.935009	valid_1's auc: 0.93184
[33]	training's auc: 0.935317

[166]	training's auc: 0.950967	valid_1's auc: 0.940182
[167]	training's auc: 0.951054	valid_1's auc: 0.940261
[168]	training's auc: 0.951198	valid_1's auc: 0.940412
[169]	training's auc: 0.951321	valid_1's auc: 0.940594
[170]	training's auc: 0.951377	valid_1's auc: 0.940608
[171]	training's auc: 0.951442	valid_1's auc: 0.940615
[172]	training's auc: 0.951518	valid_1's auc: 0.940594
[173]	training's auc: 0.951564	valid_1's auc: 0.940619
[174]	training's auc: 0.951612	valid_1's auc: 0.940622
[175]	training's auc: 0.951704	valid_1's auc: 0.940642
[176]	training's auc: 0.951791	valid_1's auc: 0.940553
[177]	training's auc: 0.951857	valid_1's auc: 0.940548
[178]	training's auc: 0.951962	valid_1's auc: 0.940609
[179]	training's auc: 0.952021	valid_1's auc: 0.940615
[180]	training's auc: 0.952096	valid_1's auc: 0.940664
[181]	training's auc: 0.952159	valid_1's auc: 0.940694
[182]	training's auc: 0.95222	valid_1's auc: 0.940661
[183]	training's auc: 0.952284	valid_1's auc: 0.940684
[184]	train

[315]	training's auc: 0.961529	valid_1's auc: 0.941809
[316]	training's auc: 0.961619	valid_1's auc: 0.941792
[317]	training's auc: 0.961704	valid_1's auc: 0.94179
[318]	training's auc: 0.96175	valid_1's auc: 0.94176
[319]	training's auc: 0.961843	valid_1's auc: 0.941773
[320]	training's auc: 0.96189	valid_1's auc: 0.941781
[321]	training's auc: 0.96196	valid_1's auc: 0.941765
[322]	training's auc: 0.962021	valid_1's auc: 0.941756
[323]	training's auc: 0.962079	valid_1's auc: 0.941715
[324]	training's auc: 0.962161	valid_1's auc: 0.941681
[325]	training's auc: 0.962243	valid_1's auc: 0.941715
[326]	training's auc: 0.962294	valid_1's auc: 0.941726
[327]	training's auc: 0.962334	valid_1's auc: 0.941713
[328]	training's auc: 0.96239	valid_1's auc: 0.941687
[329]	training's auc: 0.96245	valid_1's auc: 0.941695
[330]	training's auc: 0.962524	valid_1's auc: 0.941674
[331]	training's auc: 0.962576	valid_1's auc: 0.941649
[332]	training's auc: 0.962627	valid_1's auc: 0.941663
[333]	training's 

[464]	training's auc: 0.96964	valid_1's auc: 0.942915
[465]	training's auc: 0.969701	valid_1's auc: 0.942929
[466]	training's auc: 0.969724	valid_1's auc: 0.942987
[467]	training's auc: 0.969757	valid_1's auc: 0.942973
[468]	training's auc: 0.969808	valid_1's auc: 0.94297
[469]	training's auc: 0.969881	valid_1's auc: 0.942963
[470]	training's auc: 0.969931	valid_1's auc: 0.94293
[471]	training's auc: 0.969994	valid_1's auc: 0.942918
[472]	training's auc: 0.970039	valid_1's auc: 0.942948
[473]	training's auc: 0.970068	valid_1's auc: 0.942937
[474]	training's auc: 0.970122	valid_1's auc: 0.942949
[475]	training's auc: 0.970181	valid_1's auc: 0.942926
[476]	training's auc: 0.97024	valid_1's auc: 0.942929
[477]	training's auc: 0.970283	valid_1's auc: 0.94297
[478]	training's auc: 0.970336	valid_1's auc: 0.942934
[479]	training's auc: 0.970376	valid_1's auc: 0.942946
[480]	training's auc: 0.970433	valid_1's auc: 0.942934
[481]	training's auc: 0.970475	valid_1's auc: 0.942956
[482]	training'

[613]	training's auc: 0.976054	valid_1's auc: 0.943128
[614]	training's auc: 0.976087	valid_1's auc: 0.943133
[615]	training's auc: 0.976124	valid_1's auc: 0.943128
[616]	training's auc: 0.976164	valid_1's auc: 0.943131
[617]	training's auc: 0.976193	valid_1's auc: 0.943125
[618]	training's auc: 0.976243	valid_1's auc: 0.943118
[619]	training's auc: 0.976273	valid_1's auc: 0.943065
[620]	training's auc: 0.976292	valid_1's auc: 0.943079
[621]	training's auc: 0.97632	valid_1's auc: 0.943086
[622]	training's auc: 0.97636	valid_1's auc: 0.943101
[623]	training's auc: 0.976399	valid_1's auc: 0.943079
[624]	training's auc: 0.976424	valid_1's auc: 0.94307
[625]	training's auc: 0.976456	valid_1's auc: 0.943071
[626]	training's auc: 0.976481	valid_1's auc: 0.943045
[627]	training's auc: 0.976509	valid_1's auc: 0.94304
[628]	training's auc: 0.976548	valid_1's auc: 0.943064
[629]	training's auc: 0.976582	valid_1's auc: 0.943043
[630]	training's auc: 0.97662	valid_1's auc: 0.943048
[631]	training'

[52]	training's auc: 0.939111	valid_1's auc: 0.939726
[53]	training's auc: 0.939183	valid_1's auc: 0.939743
[54]	training's auc: 0.939339	valid_1's auc: 0.93983
[55]	training's auc: 0.939602	valid_1's auc: 0.939998
[56]	training's auc: 0.939764	valid_1's auc: 0.939896
[57]	training's auc: 0.939805	valid_1's auc: 0.939867
[58]	training's auc: 0.93999	valid_1's auc: 0.939953
[59]	training's auc: 0.940039	valid_1's auc: 0.939918
[60]	training's auc: 0.940101	valid_1's auc: 0.939699
[61]	training's auc: 0.940175	valid_1's auc: 0.939573
[62]	training's auc: 0.940365	valid_1's auc: 0.939582
[63]	training's auc: 0.940502	valid_1's auc: 0.939686
[64]	training's auc: 0.940725	valid_1's auc: 0.939824
[65]	training's auc: 0.940781	valid_1's auc: 0.939713
[66]	training's auc: 0.940834	valid_1's auc: 0.939713
[67]	training's auc: 0.940932	valid_1's auc: 0.939757
[68]	training's auc: 0.941069	valid_1's auc: 0.939822
[69]	training's auc: 0.941232	valid_1's auc: 0.939771
[70]	training's auc: 0.941352	

[202]	training's auc: 0.95377	valid_1's auc: 0.943411
[203]	training's auc: 0.953866	valid_1's auc: 0.94336
[204]	training's auc: 0.953932	valid_1's auc: 0.943362
[205]	training's auc: 0.954004	valid_1's auc: 0.943377
[206]	training's auc: 0.95408	valid_1's auc: 0.943446
[207]	training's auc: 0.954162	valid_1's auc: 0.943453
[208]	training's auc: 0.954261	valid_1's auc: 0.943458
[209]	training's auc: 0.954345	valid_1's auc: 0.94344
[210]	training's auc: 0.954401	valid_1's auc: 0.943404
[211]	training's auc: 0.954485	valid_1's auc: 0.943351
[212]	training's auc: 0.95454	valid_1's auc: 0.943365
[213]	training's auc: 0.954605	valid_1's auc: 0.943383
[214]	training's auc: 0.954687	valid_1's auc: 0.943477
[215]	training's auc: 0.954783	valid_1's auc: 0.943476
[216]	training's auc: 0.954867	valid_1's auc: 0.943465
[217]	training's auc: 0.954958	valid_1's auc: 0.943501
[218]	training's auc: 0.95502	valid_1's auc: 0.943551
[219]	training's auc: 0.955063	valid_1's auc: 0.943519
[220]	training's

[351]	training's auc: 0.9641	valid_1's auc: 0.944084
[352]	training's auc: 0.964154	valid_1's auc: 0.944113
[353]	training's auc: 0.96421	valid_1's auc: 0.944089
[354]	training's auc: 0.964285	valid_1's auc: 0.944098
[355]	training's auc: 0.964348	valid_1's auc: 0.944096
[356]	training's auc: 0.964443	valid_1's auc: 0.9442
[357]	training's auc: 0.964488	valid_1's auc: 0.944197
[358]	training's auc: 0.964565	valid_1's auc: 0.944248
[359]	training's auc: 0.964618	valid_1's auc: 0.944225
[360]	training's auc: 0.964674	valid_1's auc: 0.944258
[361]	training's auc: 0.964732	valid_1's auc: 0.944291
[362]	training's auc: 0.964766	valid_1's auc: 0.944287
[363]	training's auc: 0.964835	valid_1's auc: 0.944323
[364]	training's auc: 0.964886	valid_1's auc: 0.944278
[365]	training's auc: 0.964931	valid_1's auc: 0.944254
[366]	training's auc: 0.964986	valid_1's auc: 0.944254
[367]	training's auc: 0.965046	valid_1's auc: 0.944237
[368]	training's auc: 0.965089	valid_1's auc: 0.944245
[369]	training'

[35]	training's auc: 0.936458	valid_1's auc: 0.922875
[36]	training's auc: 0.936662	valid_1's auc: 0.922904
[37]	training's auc: 0.937168	valid_1's auc: 0.92337
[38]	training's auc: 0.937472	valid_1's auc: 0.923676
[39]	training's auc: 0.937649	valid_1's auc: 0.923861
[40]	training's auc: 0.937772	valid_1's auc: 0.923864
[41]	training's auc: 0.937966	valid_1's auc: 0.924214
[42]	training's auc: 0.93804	valid_1's auc: 0.92446
[43]	training's auc: 0.938077	valid_1's auc: 0.924183
[44]	training's auc: 0.938223	valid_1's auc: 0.923972
[45]	training's auc: 0.938303	valid_1's auc: 0.923967
[46]	training's auc: 0.938386	valid_1's auc: 0.924283
[47]	training's auc: 0.938551	valid_1's auc: 0.924241
[48]	training's auc: 0.938685	valid_1's auc: 0.92452
[49]	training's auc: 0.938842	valid_1's auc: 0.924467
[50]	training's auc: 0.939042	valid_1's auc: 0.924817
[51]	training's auc: 0.939231	valid_1's auc: 0.924728
[52]	training's auc: 0.939323	valid_1's auc: 0.924924
[53]	training's auc: 0.939411	va

[185]	training's auc: 0.952779	valid_1's auc: 0.931266
[186]	training's auc: 0.952866	valid_1's auc: 0.931352
[187]	training's auc: 0.952938	valid_1's auc: 0.931439
[188]	training's auc: 0.953019	valid_1's auc: 0.931459
[189]	training's auc: 0.953109	valid_1's auc: 0.931507
[190]	training's auc: 0.95315	valid_1's auc: 0.931449
[191]	training's auc: 0.953193	valid_1's auc: 0.931476
[192]	training's auc: 0.953254	valid_1's auc: 0.93153
[193]	training's auc: 0.953325	valid_1's auc: 0.931558
[194]	training's auc: 0.953399	valid_1's auc: 0.931647
[195]	training's auc: 0.953448	valid_1's auc: 0.931632
[196]	training's auc: 0.953544	valid_1's auc: 0.931683
[197]	training's auc: 0.95362	valid_1's auc: 0.931706
[198]	training's auc: 0.953698	valid_1's auc: 0.931738
[199]	training's auc: 0.953796	valid_1's auc: 0.931812
[200]	training's auc: 0.953847	valid_1's auc: 0.931822
[201]	training's auc: 0.953901	valid_1's auc: 0.931786
[202]	training's auc: 0.95397	valid_1's auc: 0.931786
[203]	training

[334]	training's auc: 0.963021	valid_1's auc: 0.93372
[335]	training's auc: 0.963091	valid_1's auc: 0.933687
[336]	training's auc: 0.963149	valid_1's auc: 0.933657
[337]	training's auc: 0.96321	valid_1's auc: 0.93372
[338]	training's auc: 0.963254	valid_1's auc: 0.933715
[339]	training's auc: 0.963288	valid_1's auc: 0.933711
[340]	training's auc: 0.963337	valid_1's auc: 0.933779
[341]	training's auc: 0.963375	valid_1's auc: 0.933789
[342]	training's auc: 0.963441	valid_1's auc: 0.933828
[343]	training's auc: 0.963501	valid_1's auc: 0.933827
[344]	training's auc: 0.963562	valid_1's auc: 0.933805
[345]	training's auc: 0.963653	valid_1's auc: 0.933861
[346]	training's auc: 0.963736	valid_1's auc: 0.933931
[347]	training's auc: 0.963795	valid_1's auc: 0.933955
[348]	training's auc: 0.963862	valid_1's auc: 0.933969
[349]	training's auc: 0.963917	valid_1's auc: 0.933917
[350]	training's auc: 0.963965	valid_1's auc: 0.933927
[351]	training's auc: 0.96402	valid_1's auc: 0.933936
[352]	training

[483]	training's auc: 0.97113	valid_1's auc: 0.935393
[484]	training's auc: 0.971165	valid_1's auc: 0.935426
[485]	training's auc: 0.9712	valid_1's auc: 0.935411
[486]	training's auc: 0.971254	valid_1's auc: 0.935401
[487]	training's auc: 0.971318	valid_1's auc: 0.935413
[488]	training's auc: 0.971353	valid_1's auc: 0.935443
[489]	training's auc: 0.97141	valid_1's auc: 0.935479
[490]	training's auc: 0.971455	valid_1's auc: 0.935489
[491]	training's auc: 0.97149	valid_1's auc: 0.935486
[492]	training's auc: 0.971542	valid_1's auc: 0.935566
[493]	training's auc: 0.971582	valid_1's auc: 0.935565
[494]	training's auc: 0.97161	valid_1's auc: 0.935599
[495]	training's auc: 0.971668	valid_1's auc: 0.935598
[496]	training's auc: 0.971736	valid_1's auc: 0.935612
[497]	training's auc: 0.97177	valid_1's auc: 0.935616
[498]	training's auc: 0.971805	valid_1's auc: 0.935636
[499]	training's auc: 0.971882	valid_1's auc: 0.935627
[500]	training's auc: 0.971912	valid_1's auc: 0.935609
[501]	training's 

[632]	training's auc: 0.977223	valid_1's auc: 0.936265
[633]	training's auc: 0.977255	valid_1's auc: 0.936252
[634]	training's auc: 0.977292	valid_1's auc: 0.936234
[635]	training's auc: 0.977318	valid_1's auc: 0.936214
[636]	training's auc: 0.977361	valid_1's auc: 0.936209
[637]	training's auc: 0.977404	valid_1's auc: 0.936251
[638]	training's auc: 0.977448	valid_1's auc: 0.936239
[639]	training's auc: 0.977476	valid_1's auc: 0.936254
[640]	training's auc: 0.977495	valid_1's auc: 0.936247
[641]	training's auc: 0.977523	valid_1's auc: 0.936237
[642]	training's auc: 0.977555	valid_1's auc: 0.936256
[643]	training's auc: 0.977598	valid_1's auc: 0.936244
[644]	training's auc: 0.977633	valid_1's auc: 0.936221
[645]	training's auc: 0.977661	valid_1's auc: 0.936183
[646]	training's auc: 0.977687	valid_1's auc: 0.936175
[647]	training's auc: 0.977734	valid_1's auc: 0.936152
[648]	training's auc: 0.977757	valid_1's auc: 0.936178
[649]	training's auc: 0.977788	valid_1's auc: 0.936188
[650]	trai

[781]	training's auc: 0.981969	valid_1's auc: 0.937004
[782]	training's auc: 0.98199	valid_1's auc: 0.937021
[783]	training's auc: 0.982022	valid_1's auc: 0.937014
[784]	training's auc: 0.982047	valid_1's auc: 0.937022
[785]	training's auc: 0.982081	valid_1's auc: 0.937006
[786]	training's auc: 0.982099	valid_1's auc: 0.937011
[787]	training's auc: 0.982127	valid_1's auc: 0.936988
[788]	training's auc: 0.982145	valid_1's auc: 0.936979
[789]	training's auc: 0.982173	valid_1's auc: 0.936956
[790]	training's auc: 0.9822	valid_1's auc: 0.936953
[791]	training's auc: 0.982229	valid_1's auc: 0.93694
[792]	training's auc: 0.982256	valid_1's auc: 0.936974
[793]	training's auc: 0.982296	valid_1's auc: 0.937007
[794]	training's auc: 0.982319	valid_1's auc: 0.937016
[795]	training's auc: 0.982347	valid_1's auc: 0.937049
[796]	training's auc: 0.982368	valid_1's auc: 0.937082
[797]	training's auc: 0.982381	valid_1's auc: 0.937067
[798]	training's auc: 0.982398	valid_1's auc: 0.93706
[799]	training'

[930]	training's auc: 0.985714	valid_1's auc: 0.936993
[931]	training's auc: 0.985741	valid_1's auc: 0.937017
[932]	training's auc: 0.985764	valid_1's auc: 0.937009
[933]	training's auc: 0.985789	valid_1's auc: 0.937004
Early stopping, best iteration is:
[833]	training's auc: 0.983342	valid_1's auc: 0.937157
[1]	training's auc: 0.892753	valid_1's auc: 0.888948
Training until validation scores don't improve for 100 rounds
[2]	training's auc: 0.909314	valid_1's auc: 0.901293
[3]	training's auc: 0.916023	valid_1's auc: 0.905118
[4]	training's auc: 0.916644	valid_1's auc: 0.905341
[5]	training's auc: 0.925998	valid_1's auc: 0.91444
[6]	training's auc: 0.925712	valid_1's auc: 0.913798
[7]	training's auc: 0.929511	valid_1's auc: 0.919733
[8]	training's auc: 0.929306	valid_1's auc: 0.919952
[9]	training's auc: 0.92862	valid_1's auc: 0.918651
[10]	training's auc: 0.929573	valid_1's auc: 0.919667
[11]	training's auc: 0.930283	valid_1's auc: 0.919908
[12]	training's auc: 0.930458	valid_1's auc: 

[145]	training's auc: 0.949962	valid_1's auc: 0.934398
[146]	training's auc: 0.950035	valid_1's auc: 0.934335
[147]	training's auc: 0.950128	valid_1's auc: 0.934418
[148]	training's auc: 0.95017	valid_1's auc: 0.934379
[149]	training's auc: 0.950249	valid_1's auc: 0.934338
[150]	training's auc: 0.950411	valid_1's auc: 0.934492
[151]	training's auc: 0.950468	valid_1's auc: 0.934476
[152]	training's auc: 0.950535	valid_1's auc: 0.934518
[153]	training's auc: 0.950599	valid_1's auc: 0.934527
[154]	training's auc: 0.950671	valid_1's auc: 0.934589
[155]	training's auc: 0.950774	valid_1's auc: 0.934533
[156]	training's auc: 0.950876	valid_1's auc: 0.93455
[157]	training's auc: 0.950948	valid_1's auc: 0.934578
[158]	training's auc: 0.950996	valid_1's auc: 0.934558
[159]	training's auc: 0.951052	valid_1's auc: 0.934569
[160]	training's auc: 0.951091	valid_1's auc: 0.934495
[161]	training's auc: 0.951147	valid_1's auc: 0.934582
[162]	training's auc: 0.951219	valid_1's auc: 0.934571
[163]	traini

[294]	training's auc: 0.960522	valid_1's auc: 0.936956
[295]	training's auc: 0.960601	valid_1's auc: 0.936994
[296]	training's auc: 0.960664	valid_1's auc: 0.937019
[297]	training's auc: 0.96072	valid_1's auc: 0.936946
[298]	training's auc: 0.960779	valid_1's auc: 0.936952
[299]	training's auc: 0.960881	valid_1's auc: 0.936911
[300]	training's auc: 0.960944	valid_1's auc: 0.936957
[301]	training's auc: 0.961016	valid_1's auc: 0.93697
[302]	training's auc: 0.961079	valid_1's auc: 0.936932
[303]	training's auc: 0.961146	valid_1's auc: 0.936948
[304]	training's auc: 0.961197	valid_1's auc: 0.936932
[305]	training's auc: 0.961252	valid_1's auc: 0.936927
[306]	training's auc: 0.961357	valid_1's auc: 0.936946
[307]	training's auc: 0.961442	valid_1's auc: 0.937012
[308]	training's auc: 0.961504	valid_1's auc: 0.936978
[309]	training's auc: 0.961579	valid_1's auc: 0.936953
[310]	training's auc: 0.961636	valid_1's auc: 0.936921
[311]	training's auc: 0.961699	valid_1's auc: 0.936955
[312]	traini

[443]	training's auc: 0.969228	valid_1's auc: 0.938707
[444]	training's auc: 0.969283	valid_1's auc: 0.938688
[445]	training's auc: 0.969316	valid_1's auc: 0.938648
[446]	training's auc: 0.969372	valid_1's auc: 0.938672
[447]	training's auc: 0.969417	valid_1's auc: 0.938639
[448]	training's auc: 0.96945	valid_1's auc: 0.938707
[449]	training's auc: 0.969495	valid_1's auc: 0.938713
[450]	training's auc: 0.969554	valid_1's auc: 0.938741
[451]	training's auc: 0.969606	valid_1's auc: 0.93878
[452]	training's auc: 0.969679	valid_1's auc: 0.938776
[453]	training's auc: 0.96974	valid_1's auc: 0.938738
[454]	training's auc: 0.969777	valid_1's auc: 0.938704
[455]	training's auc: 0.96982	valid_1's auc: 0.938711
[456]	training's auc: 0.969881	valid_1's auc: 0.938752
[457]	training's auc: 0.969929	valid_1's auc: 0.938768
[458]	training's auc: 0.969977	valid_1's auc: 0.938786
[459]	training's auc: 0.970012	valid_1's auc: 0.938783
[460]	training's auc: 0.970065	valid_1's auc: 0.938731
[461]	training

[592]	training's auc: 0.975743	valid_1's auc: 0.939119
[593]	training's auc: 0.975786	valid_1's auc: 0.939107
[594]	training's auc: 0.975811	valid_1's auc: 0.939103
[595]	training's auc: 0.975886	valid_1's auc: 0.939125
[596]	training's auc: 0.975947	valid_1's auc: 0.939101
[597]	training's auc: 0.975987	valid_1's auc: 0.939061
[598]	training's auc: 0.976025	valid_1's auc: 0.939058
[599]	training's auc: 0.976052	valid_1's auc: 0.939051
[600]	training's auc: 0.976078	valid_1's auc: 0.939045
[601]	training's auc: 0.976117	valid_1's auc: 0.939094
[602]	training's auc: 0.976161	valid_1's auc: 0.939082
[603]	training's auc: 0.976197	valid_1's auc: 0.939091
[604]	training's auc: 0.976236	valid_1's auc: 0.939087
[605]	training's auc: 0.976288	valid_1's auc: 0.93908
[606]	training's auc: 0.976316	valid_1's auc: 0.939103
[607]	training's auc: 0.976358	valid_1's auc: 0.939115
[608]	training's auc: 0.976391	valid_1's auc: 0.939079
[609]	training's auc: 0.976426	valid_1's auc: 0.939108
[610]	train

[71]	training's auc: 0.943279	valid_1's auc: 0.919505
[72]	training's auc: 0.943407	valid_1's auc: 0.919564
[73]	training's auc: 0.943502	valid_1's auc: 0.919606
[74]	training's auc: 0.943581	valid_1's auc: 0.91969
[75]	training's auc: 0.943747	valid_1's auc: 0.919555
[76]	training's auc: 0.943841	valid_1's auc: 0.919461
[77]	training's auc: 0.943895	valid_1's auc: 0.919563
[78]	training's auc: 0.944152	valid_1's auc: 0.919734
[79]	training's auc: 0.944268	valid_1's auc: 0.919685
[80]	training's auc: 0.94442	valid_1's auc: 0.919578
[81]	training's auc: 0.944641	valid_1's auc: 0.919531
[82]	training's auc: 0.94476	valid_1's auc: 0.919681
[83]	training's auc: 0.94489	valid_1's auc: 0.919885
[84]	training's auc: 0.945036	valid_1's auc: 0.919901
[85]	training's auc: 0.945163	valid_1's auc: 0.919885
[86]	training's auc: 0.945277	valid_1's auc: 0.919937
[87]	training's auc: 0.945395	valid_1's auc: 0.919803
[88]	training's auc: 0.945499	valid_1's auc: 0.91981
[89]	training's auc: 0.945633	val

[221]	training's auc: 0.956845	valid_1's auc: 0.923306
[222]	training's auc: 0.956927	valid_1's auc: 0.923323
[223]	training's auc: 0.956999	valid_1's auc: 0.923442
[224]	training's auc: 0.957043	valid_1's auc: 0.923426
[225]	training's auc: 0.957103	valid_1's auc: 0.923425
[226]	training's auc: 0.957154	valid_1's auc: 0.923417
[227]	training's auc: 0.957206	valid_1's auc: 0.923415
[228]	training's auc: 0.957265	valid_1's auc: 0.92349
[229]	training's auc: 0.957346	valid_1's auc: 0.923526
[230]	training's auc: 0.957431	valid_1's auc: 0.92355
[231]	training's auc: 0.957492	valid_1's auc: 0.923557
[232]	training's auc: 0.95754	valid_1's auc: 0.923513
[233]	training's auc: 0.957583	valid_1's auc: 0.923478
[234]	training's auc: 0.957636	valid_1's auc: 0.923481
[235]	training's auc: 0.957698	valid_1's auc: 0.92346
[236]	training's auc: 0.957783	valid_1's auc: 0.923481
[237]	training's auc: 0.957852	valid_1's auc: 0.923529
[238]	training's auc: 0.957946	valid_1's auc: 0.923518
[239]	training

[370]	training's auc: 0.966312	valid_1's auc: 0.924603
[371]	training's auc: 0.96634	valid_1's auc: 0.924634
[372]	training's auc: 0.966397	valid_1's auc: 0.924566
[373]	training's auc: 0.966454	valid_1's auc: 0.924578
[374]	training's auc: 0.9665	valid_1's auc: 0.924578
[375]	training's auc: 0.966553	valid_1's auc: 0.924592
[376]	training's auc: 0.96659	valid_1's auc: 0.924575
[377]	training's auc: 0.966636	valid_1's auc: 0.924611
[378]	training's auc: 0.966697	valid_1's auc: 0.924609
[379]	training's auc: 0.966746	valid_1's auc: 0.924558
[380]	training's auc: 0.96679	valid_1's auc: 0.924557
[381]	training's auc: 0.966846	valid_1's auc: 0.924536
[382]	training's auc: 0.966889	valid_1's auc: 0.924505
[383]	training's auc: 0.966944	valid_1's auc: 0.924523
[384]	training's auc: 0.966977	valid_1's auc: 0.924545
[385]	training's auc: 0.967033	valid_1's auc: 0.924596
[386]	training's auc: 0.967088	valid_1's auc: 0.924652
[387]	training's auc: 0.967138	valid_1's auc: 0.92466
[388]	training's

[519]	training's auc: 0.973666	valid_1's auc: 0.925262
[520]	training's auc: 0.973688	valid_1's auc: 0.925241
[521]	training's auc: 0.973742	valid_1's auc: 0.925251
[522]	training's auc: 0.973774	valid_1's auc: 0.925275
[523]	training's auc: 0.973817	valid_1's auc: 0.925252
[524]	training's auc: 0.973865	valid_1's auc: 0.925242
[525]	training's auc: 0.973893	valid_1's auc: 0.92527
[526]	training's auc: 0.973933	valid_1's auc: 0.925234
[527]	training's auc: 0.973985	valid_1's auc: 0.925248
[528]	training's auc: 0.974029	valid_1's auc: 0.925218
[529]	training's auc: 0.974077	valid_1's auc: 0.925207
[530]	training's auc: 0.974114	valid_1's auc: 0.925221
[531]	training's auc: 0.974148	valid_1's auc: 0.925234
[532]	training's auc: 0.974192	valid_1's auc: 0.925259
[533]	training's auc: 0.974233	valid_1's auc: 0.925266
[534]	training's auc: 0.974283	valid_1's auc: 0.925286
[535]	training's auc: 0.974321	valid_1's auc: 0.9253
[536]	training's auc: 0.974363	valid_1's auc: 0.92531
[537]	training